export const corporateUserDetailsMetaData = {
  form: {
    name: "corporateuserRegistration",
    label: "Corporate User Registration ",
    resetFieldOnUnmount: false,
    validationRun: "onBlur",
    render: {
      ordering: "auto",
      renderType: "simple",
      gridConfig: {
        item: {
          xs: 12,
          sm: 12,
          md: 12,
        },
        container: {
          direction: "row",
          spacing: 2,
        },
      },
    },
  },
  fields: [
    {
      render: { componentType: "textField" },
      name: "CUSTOMER_ID",
      label: "Customer ID",
      placeholder: " ",
      type: "text",
      required: true,
      maxLength: 300,
      showMaxLength: false,
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      autoComplete: "off",
    },
    {
      render: { componentType: "textField" },
      name: "DOMAIN_NM",
      label: "Domain Name",
      placeholder: " ",
      type: "text",
      required: true,
      maxLength: 300,
      showMaxLength: false,
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      autoComplete: "off",
    },
    {
      render: { componentType: "textField" },
      name: "NAME",
      label: "Name",
      placeholder: " ",
      type: "text",
      required: true,
      maxLength: 300,
      showMaxLength: false,
      GridProps: { xs: 12, md: 3, sm: 3 },
      fullWidth: true,
      autoComplete: "off",
    },
    {
      render: { componentType: "textField" },
      name: "ADDRESS",
      label: "Address",
      placeholder: " ",
      type: "text",
      required: true,
      maxLength: 300,
      showMaxLength: false,
      GridProps: { xs: 12, md: 5, sm: 5 },
      fullWidth: true,
      autoComplete: "off",
    },
    {
      render: { componentType: "textField" },
      name: "PAN_NO",
      label: "PAN No",
      placeholder: " ",
      type: "text",
      required: true,
      maxLength: 300,
      showMaxLength: false,
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      autoComplete: "off",
    },
    {
      render: { componentType: "textField" },
      name: "MOBILE_NO",
      label: "Mobile No.",
      placeholder: " ",
      type: "text",
      required: true,
      maxLength: 300,
      showMaxLength: false,
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      autoComplete: "off",
    },
    {
      render: { componentType: "textField" },
      name: "EMAIL_ID",
      label: "Email ID",
      placeholder: " ",
      type: "text",
      required: true,
      maxLength: 300,
      showMaxLength: false,
      GridProps: { xs: 12, md: 3, sm: 3 },
      fullWidth: true,
      autoComplete: "off",
    },
    {
      render: { componentType: "textField" },
      name: "PER_DAY_LIMIT",
      label: "Per Day Max Limit",
      placeholder: " ",
      type: "text",
      required: true,
      maxLength: 300,
      showMaxLength: false,
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      autoComplete: "off",
    },
    {
      render: { componentType: "checkbox" },
      name: "ACTIVE",
      label: "Active",
      // defaultValue: true,
      GridProps: { xs: 6, md: 1, sm: 1 },
      // __EDIT__: { render: { componentType: "checkbox" } },
    },
    {
      render: { componentType: "formbutton" },
      name: "LIMIT",
      label: "Limit",
      placeholder: " ",
      type: "text",
      required: true,
      maxLength: 300,
      showMaxLength: false,
      GridProps: { xs: 6, md: 2, sm: 2 },
      fullWidth: true,
      autoComplete: "off",
    },
  ],
};
