import { GridMetaDataType } from "components/dataTableStatic";
import { GeneralAPI } from "registry/fns/functions";

export const IdtpChargeConfigGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "IDTP Charge Configuration",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 25, 50],
    defaultPageSize: 15,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
    hiddenFlag: "_hidden",
  },
  filters: [],
  columns: [
    {
      accessor: "id",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "rigth",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 120,
      isAutoSequence: true,
    },
    {
      accessor: "TRN_TYPE",
      columnName: "Service*",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      autoComplete: "off",
      width: 150,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "RECEIVER_FITYPE",
      columnName: "Receiver FI*",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      autoComplete: "off",
      placeholder: "",
      width: 100,
      minWidth: 150,
      maxWidth: 400,
    },
    {
      accessor: "DESCRIPTION",
      columnName: "Description",
      sequence: 4,
      alignment: "left",
      componentType: "editableTextField",
      placeholder: "",
      autoComplete: "off",
      width: 200,
      minWidth: 100,
      maxWidth: 300,
      isReadOnly: true,
    },

    {
      accessor: "SERVICE_CHARGE_TEMPLT",
      columnName: "Service Charge Template",
      sequence: 8,
      alignment: "left",
      componentType: "editableAutocomplete",
      defaultOptionLabel: "Select Service Charge Template",
      placeholder: "Select Service Charge Template",
      options: () => GeneralAPI.GetChargeTemplates(),
      _optionsKey: "GetChargeTemplates",
      width: 170,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "VAT_PERC",
      columnName: "VAT Percentage",
      sequence: 8,
      alignment: "left",
      autoComplete: "off",
      componentType: "editableNumberFormat",
      placeholder: "",
      width: 140,
      minWidth: 80,
      maxWidth: 200,
    },
  ],
};
export const IdtpChargeConfigGridViewMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "IDTP Charge Configuration",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 25, 50],
    defaultPageSize: 15,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
    hiddenFlag: "_hidden",
  },
  filters: [],
  columns: [
    {
      accessor: "id",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "rigth",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 120,
      isAutoSequence: true,
    },
    {
      accessor: "TRN_TYPE",
      columnName: "Service*",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      autoComplete: "off",
      width: 150,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "RECEIVER_FITYPE",
      columnName: "Receiver FI*",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      autoComplete: "off",
      placeholder: "",
      width: 100,
      minWidth: 150,
      maxWidth: 400,
    },
    {
      accessor: "DESCRIPTION",
      columnName: "Description",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      autoComplete: "off",
      width: 200,
      minWidth: 100,
      maxWidth: 300,
      isReadOnly: true,
    },

    {
      accessor: "SERVICE_CHARGE_TEMPLT",
      columnName: "Service Charge Template",
      sequence: 8,
      alignment: "left",
      componentType: "disableSelect",
      defaultOptionLabel: "Select Service Charge Template",
      options: () => GeneralAPI.GetChargeTemplates(),
      _optionsKey: "GetChargeTemplates",
      placeholder: "",
      width: 170,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "VAT_PERC",
      columnName: "VAT Percentage",
      sequence: 8,
      alignment: "left",
      autoComplete: "off",
      componentType: "default",
      placeholder: "",
      width: 140,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "CONFIRM_STATUS",
      columnName: "Status",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 160,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "Modified Date",
      sequence: 10,
      alignment: "left",
      componentType: "date",
      placeholder: "",
      width: 140,
      minWidth: 80,
      maxWidth: 200,
      dateFormat: "dd/MM/yyyy HH:mm:ss",
    },
    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Modified By",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 140,
      minWidth: 80,
      maxWidth: 200,
    },
  ],
};

export const IdtpChargeConfigConfirmGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "IDTP Charge Configuration Confirmation",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 25, 50],
    defaultPageSize: 15,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: true,
    hiddenFlag: "_hidden",
  },
  filters: [],
  columns: [
    {
      accessor: "id",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "rigth",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 120,
      isAutoSequence: true,
    },
    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "Modified Date",
      sequence: 2,
      alignment: "left",
      componentType: "date",
      placeholder: "",
      width: 150,
      minWidth: 100,
      maxWidth: 250,
      dateFormat: "dd/MM/yyyy HH:mm:ss",
    },
    {
      accessor: "TRN_TYPE",
      columnName: "Service",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 150,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "RECEIVER_FITYPE",
      columnName: "Receiver FI",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 100,
      minWidth: 150,
      maxWidth: 400,
    },
    {
      accessor: "DESCRIPTION",
      columnName: "Description",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 200,
      minWidth: 100,
      maxWidth: 300,
      isReadOnly: true,
    },

    {
      accessor: "SERVICE_CHARGE_TEMPLT",
      columnName: "New Service Charge Template",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 200,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "OLD_SERVICE_CHRG_TEMPLT",
      columnName: "Old Service Charge Template",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 200,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "VAT_PERC",
      columnName: "New VAT Percentage",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 170,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "OLD_VAT_PERC",
      columnName: "Old VAT Percentage",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 170,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Modified By",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 110,
      minWidth: 80,
      maxWidth: 200,
    },
  ],
};
