import { GridMetaDataType } from "components/dataTableStatic";
export const UserBlockGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Admin Panel Blocked User Release",
    rowIdColumn: "USER_NAME",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "64vh",
      max: "64vh",
    },
    allowFilter: true,
    allowColumnHiding: true,
    allowRowSelection: true,
  },
  filters: [
    {
      accessor: "USER_NAME",
      columnName: "User Name",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "id",
      columnName: "Sr. No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 150,
      maxWidth: 200,
      isAutoSequence: true,
    },
    {
      accessor: "USER_NAME",
      columnName: "Blocked User Name",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 600,
    },
    {
      accessor: "FAILURE_ATTEMPT",
      columnName: "Failure Attempt Count",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 600,
    },
    {
      columnName: "View Details",
      componentType: "buttonRowCell",
      accessor: "VIEW_DETAIL",
      sequence: 3,
      buttonLabel: "...",
      isVisible: true,
      width: 100,
      minWidth: 50,
      maxWidth: 150,
    },
  ],
};
