import { GridMetaDataType } from "components/dataTableStatic";
export const UserReleaseGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Admin Panel User Release",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "60vh",
      max: "60vh",
    },
    allowFilter: true,
    allowColumnHiding: true,
    allowRowSelection: true,
  },
  filters: [
    {
      accessor: "USERNAME",
      columnName: "User Name",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "LOGIN_DT",
      columnName: "Login Time",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "PASSWORD",
      columnName: "Operation",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "TRAN_CD",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "left",
      // isVisible: false,
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "USERNAME",
      columnName: "User Name",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 100,
      maxWidth: 600,
    },

    {
      accessor: "LOGIN_DT",
      columnName: "Login Date-Time",
      sequence: 3,
      alignment: "left",
      componentType: "date",
      dateFormat: "dd/MM/yyyy HH:mm:ss",
      width: 150,
      minWidth: 100,
      maxWidth: 350,
    },
    {
      accessor: "PASSWORD",
      columnName: "Operation",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 450,
    },
    {
      accessor: "REMARKS",
      columnName: "Blocked Reason",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 350,
      minWidth: 100,
      maxWidth: 450,
    },
    // {
    //   accessor: "WEB_APPL_SESS_ID",
    //   columnName: "Application Session ID",
    //   sequence: 7,
    //   alignment: "left",
    //   componentType: "default",
    //   width: 200,
    //   minWidth: 100,
    //   maxWidth: 450,
    // },
    {
      accessor: "LOGOUT_DT",
      columnName: "Logout Date-Time",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 350,
    },
  ],
};
