import { GridMetaDataType } from "components/dataTableStatic";

export const LoanLockRelReqGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Loan Release Lock Request",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "63vh",
      max: "70vh",
    },
    allowFilter: true,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: true,
  },
  filters: [
    {
      accessor: "CUSTOM_NM",
      columnName: "Login ID",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        sm: 12,
        md: 12,
      },
    },
    {
      accessor: "APPLICANT_NM",
      columnName: "Applicant Name",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        sm: 12,
        md: 12,
      },
    },
    {
      accessor: "TRAN_DT",
      columnName: "Request Date",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        sm: 12,
        md: 12,
      },
    },
    {
      accessor: "FD_ACCOUNT",
      columnName: "FD Account",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        sm: 12,
        md: 12,
      },
    },
    {
      accessor: "CONF_STATUS",
      columnName: "Status",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        sm: 12,
        md: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "sr_no",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 70,
      maxWidth: 200,
      isAutoSequence: true,
    },
    {
      accessor: "CUSTOM_NM",
      columnName: "Login ID",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 140,
      maxWidth: 180,
    },
    {
      accessor: "APPLICANT_NM",
      columnName: "Applicant Name",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 140,
      maxWidth: 180,
    },
    {
      accessor: "TRAN_DT",
      columnName: "Request Date",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy HH:mm:ss",
      width: 170,
      minWidth: 120,
      maxWidth: 180,
    },
    {
      accessor: "FD_ACCOUNT",
      columnName: "FD Account",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "LOAN_AMOUNT",
      columnName: "Loan Amount",
      sequence: 6,
      alignment: "right",
      componentType: "currency",
      width: 120,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "EMI_AMOUNT",
      columnName: "EMI Amount",
      sequence: 7,
      alignment: "right",
      componentType: "currency",
      width: 120,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "CONF_STATUS",
      columnName: "Status",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "ASSIGNED_TO",
      columnName: "Lock By",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 150,
    },
  ],
};
