import { GridMetaDataType } from "components/dataTableStatic";
export const ReleaseUserMercGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "",
    rowIdColumn: "CUSTOM_USER_NM",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    // hideHeader: true,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "45vh",
      max: "45vh",
    },
    allowFilter: true,
    // allowColumnHiding: true,
  },
  filters: [
    {
      accessor: "CUSTOM_USER_NM",
      columnName: "Login ID",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "BLOCK_DATE",
      columnName: "Block Date",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "BLOCK_REASON",
      columnName: "Block Reason",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "sr_no",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 80,
      maxWidth: 200,
      isAutoSequence: true,
    },
    {
      accessor: "CUSTOM_USER_NM",
      columnName: "Login ID",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },

    {
      accessor: "BLOCK_DATE",
      columnName: "Block Date",
      sequence: 4,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy hh:mm:ss",
      width: 150,
      minWidth: 140,
      maxWidth: 200,
    },

    {
      accessor: "BLOCK_REASON",
      columnName: "Block Reason",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "LOCK_TYPE",
      columnName: "Block Reason",
      isVisible: false,
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "TRAN_CD",
      columnName: "Block Reason",
      isVisible: false,
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "SR_CD",
      columnName: "Block Reason",
      isVisible: false,
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
};
