import { MasterDetailsMetaData } from "components/formcomponent/masterDetails/types";
import { GridMetaDataType } from "components/dataTableStatic";
export const MsPropertiesDetailsMetaData: MasterDetailsMetaData = {
  masterForm: {
    form: {
      name: "editMsProperties",
      label: "MS Properties Configuration",
      resetFieldOnUnmount: false,
      validationRun: "onBlur",
      render: {
        ordering: "auto",
        renderType: "simple",
        gridConfig: {
          item: {
            xs: 12,
            sm: 4,
            md: 4,
          },
          componentProps: {
            textField: {
              fullWidth: true,
            },
            select: {
              fullWidth: true,
            },
            datePicker: {
              fullWidth: true,
            },
            numberFormat: {
              fullWidth: true,
            },
            inputMask: {
              fullWidth: true,
            },
            datetimePicker: {
              fullWidth: true,
            },
          },
          container: {
            direction: "row",
            spacing: 1,
          },
        },
      },
    },
    fields: [
      {
        render: { componentType: "textField" },
        name: "APPLICATION_NAME",
        label: "Application Name",
        placeholder: "",
        autoComplete: "off",
        required: true,
        maxLength: 300,
        showMaxLength: false,
        GridProps: { xs: 12, md: 4, sm: 4 },
        fullWidth: true,
        __EDIT__: { isReadOnly: true },
      },
      {
        render: { componentType: "textField" },
        name: "PROFILE_NM",
        label: "Profile Name",
        placeholder: "",
        autoComplete: "off",
        required: true,
        maxLength: 300,
        showMaxLength: false,
        GridProps: { xs: 12, md: 4, sm: 4 },
        fullWidth: true,
        __EDIT__: { isReadOnly: true },
      },
      {
        render: { componentType: "textField" },
        name: "LABEL",
        label: "Label",
        placeholder: "",
        autoComplete: "off",
        required: true,
        maxLength: 300,
        __EDIT__: { isReadOnly: true },
        showMaxLength: false,
        GridProps: { xs: 12, md: 4, sm: 4 },
        fullWidth: true,
      },
      // {
      //   render: { componentType: "hidden" },
      //   name: "TRAN_CD",
      // },
    ],
  },
  detailsGrid: {
    gridConfig: {
      dense: true,
      gridLabel: "MsPropertiesDetails",
      rowIdColumn: "SR_CD",
      defaultColumnConfig: { width: 150, maxWidth: 250, minWidth: 100 },
      allowColumnReordering: true,
      hideHeader: true,
      disableGroupBy: true,
      enablePagination: true,
      containerHeight: { min: "50vh", max: "50vh" },
      allowRowSelection: false,
      hiddenFlag: "_hidden",
      disableLoader: true,
      pageSizes: [10, 20, 30],
      defaultPageSize: 10,
    },
    columns: [
      {
        accessor: "SR_CD",
        columnName: "Sr. No",
        componentType: "default",
        sequence: 1,
        alignment: "right",
        width: 70,
        maxWidth: 150,
        minWidth: 40,
      },
      {
        accessor: "KEY_NM",
        columnName: "Key",
        sequence: 2,
        componentType: "default",
        placeholder: "",
        width: 250,
        minWidth: 200,
        maxWidth: 300,
        // schemaValidation: {
        //   type: "string",
        //   rules: [{ name: "required", params: ["This field is required"] }],
        // },
      },
      {
        accessor: "KEY_VALUE",
        columnName: "Value",
        sequence: 3,
        componentType: "editableTextField",
        autoComplete: "off",
        placeholder: "",
        width: 200,
        minWidth: 100,
        maxWidth: 250,
        // schemaValidation: {
        //   type: "string",
        //   rules: [{ name: "required", params: ["This field is required"] }],
        // },
      },
      {
        accessor: "DESCRIPTION",
        columnName: "Description",
        sequence: 4,
        componentType: "editableTextField",
        placeholder: "",
        autoComplete: "off",
        width: 200,
        minWidth: 100,
        maxWidth: 350,
      },

      // {
      //   columnName: "Action",
      //   componentType: "deleteRowCell",
      //   accessor: "_hidden",
      //   sequence: 12,
      // },
    ],
  },
};

export const MsPropertiesDetailsMetaDatas: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "MS Properties Configuration",
    rowIdColumn: "SR_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 15, 25, 50],
    defaultPageSize: 10,
    containerHeight: {
      min: "47vh",
      max: "47vh",
    },
    allowFilter: true,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: true,
    hiddenFlag: "_hidden",
    disableLoader: false,
  },
  filters: [],
  columns: [
    {
      accessor: "SR_CD",
      columnName: "Sr. No",
      componentType: "default",
      sequence: 1,
      alignment: "right",
      width: 70,
      maxWidth: 150,
      minWidth: 40,
      isAutoSequence: true,
    },
    {
      accessor: "KEY_NM",
      columnName: "Key",
      sequence: 2,
      componentType: "default",
      placeholder: "",
      width: 250,
      minWidth: 200,
      maxWidth: 300,
      // schemaValidation: {
      //   type: "string",
      //   rules: [{ name: "required", params: ["This field is required"] }],
      // },
    },
    {
      accessor: "KEY_VALUE",
      columnName: "Value",
      sequence: 3,
      componentType: "default",
      autoComplete: "off",
      placeholder: "",
      width: 200,
      minWidth: 100,
      maxWidth: 250,
      // schemaValidation: {
      //   type: "string",
      //   rules: [{ name: "required", params: ["This field is required"] }],
      // },
    },
    {
      accessor: "DESCRIPTION",
      columnName: "Description",
      sequence: 4,
      componentType: "default",
      placeholder: "",
      autoComplete: "off",
      width: 200,
      minWidth: 100,
      maxWidth: 350,
    },

    // {
    //   columnName: "Action",
    //   componentType: "deleteRowCell",
    //   accessor: "_hidden",
    //   sequence: 12,
    // },
  ],
};

export const MSProperitiesFormMetadata = {
  form: {
    name: "MSProperitiesForm",
    label: "MS Properties Configuration",
    resetFieldOnUnmount: false,
    validationRun: "onBlur",
    submitAction: "home",
    render: {
      ordering: "auto",
      renderType: "simple",
      gridConfig: {
        item: {
          xs: 12,
          sm: 4,
          md: 4,
        },
        container: {
          direction: "row",
          spacing: 1,
        },
      },
    },
    componentProps: {
      textField: {
        fullWidth: true,
      },
      select: {
        fullWidth: true,
      },
      datePicker: {
        fullWidth: true,
      },
      numberFormat: {
        fullWidth: true,
      },
      inputMask: {
        fullWidth: true,
      },
      datetimePicker: {
        fullWidth: true,
      },
    },
  },
  fields: [
    {
      render: { componentType: "textField" },
      name: "KEY_NM",
      label: "Key",
      placeholder: "Enter Key",
      autoComplete: "off",
      required: true,
      maxLength: 300,
      showMaxLength: false,
      GridProps: { xs: 12, md: 4, sm: 4 },
      fullWidth: true,
      __EDIT__: { isReadOnly: true },
      schemaValidation: {
        type: "string",
        rules: [{ name: "required", params: ["This field is required"] }],
      },
      //@ts-ignore
      isFieldFocused: true,
    },
    {
      render: { componentType: "textField" },
      name: "KEY_VALUE",
      label: "Value",
      placeholder: "Enter Value",
      autoComplete: "off",
      // required: true,
      maxLength: 300,
      showMaxLength: false,
      GridProps: { xs: 12, md: 4, sm: 4 },
      fullWidth: true,
    },
    {
      render: { componentType: "textField" },
      name: "DESCRIPTION",
      label: "Description",
      placeholder: "Enter Description",
      autoComplete: "off",
      // required: true,
      maxLength: 300,
      showMaxLength: false,
      GridProps: { xs: 12, md: 4, sm: 4 },
      fullWidth: true,
    },
    {
      render: { componentType: "hidden" },
      name: "APPLICATION_NAME",
      label: "",
      placeholder: "",
      autoComplete: "off",
      required: true,
      maxLength: 300,
      showMaxLength: false,
      GridProps: { xs: 12, md: 4, sm: 4 },
      fullWidth: true,
    },
    {
      render: { componentType: "hidden" },
      name: "PROFILE_NM",
      label: "Profile Name",
      placeholder: "",
      autoComplete: "off",
      required: true,
      maxLength: 300,
      showMaxLength: false,
      GridProps: { xs: 12, md: 4, sm: 4 },
      fullWidth: true,
    },
    {
      render: { componentType: "hidden" },
      name: "LABEL",
      label: "Label",
      placeholder: "",
      autoComplete: "off",
      required: true,
      maxLength: 300,
      showMaxLength: false,
      GridProps: { xs: 12, md: 4, sm: 4 },
      fullWidth: true,
    },
  ],
};
