import { GridMetaDataType } from "components/dataTableStatic";

export const VirtualCardImageGrid: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Virtual Card Image Configuration",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    containerHeight: { min: "65vh", max: "65vh" },
    pageSizes: [15, 20, 30],
    defaultPageSize: 15,
    allowFilter: true,
  },
  filters: [
    {
      accessor: "IMAGE_ID",
      columnName: "Image ID",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "ACTIVE",
      columnName: "Active",
      filterComponentType: "optionsFilter",
      filterProps: {
        options: [
          { label: "Yes", value: "Y" },
          { label: "No", value: "N" },
        ],
      },
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "TRAN_CD",
      isAutoSequence: true,
      columnName: "Sr. No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 70,
      maxWidth: 120,
    },
    {
      accessor: "IMAGE_ID",
      columnName: "Image ID",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 70,
      maxWidth: 250,
    },
    {
      accessor: "ACTIVE",
      columnName: "Active",
      sequence: 3,
      alignment: "left",
      componentType: "editableCheckbox",
      width: 130,
      minWidth: 100,
      maxWidth: 200,
      isReadOnly: true,
    },
    // {
    //     accessor: "CARD_IMAGE",
    //     columnName: "Card Image",
    //     sequence: 12,
    //     alignment: "left",
    //     componentType: "icondefault",
    //     width: 130,
    //     minWidth: 100,
    //     maxWidth: 200,
    //     isReadOnly: true,
    // },
    {
      accessor: "CONFIRM_STATUS",
      columnName: "Confirm Status",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 200,
      maxWidth: 250,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "Entered By",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 300,
    },
    {
      accessor: "ENTERED_DATE",
      columnName: "Entered Date",
      sequence: 7,
      // isVisible: false,
      alignment: "left",
      componentType: "date",
      dateFormat: "dd/MM/yyyy HH:mm:ss",
      width: 150,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Modified By",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 300,
    },
    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "Modified Date",
      sequence: 9,
      alignment: "left",
      componentType: "date",
      dateFormat: "dd/MM/yyyy HH:mm:ss",
      width: 120,
      minWidth: 170,
      maxWidth: 200,
    },
  ],
};
