import { GridMetaDataType } from "components/dataTableStatic";

export const WebReroutingConfigGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Web Rerouting Configuration",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    containerHeight: { min: "65vh", max: "65vh" },
    pageSizes: [15, 20, 30],
    defaultPageSize: 15,
    allowFilter: true,
  },
  filters: [
    {
      accessor: "DISP_MENU_FLAG",
      columnName: "Action Menu",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "DESCRIPTION",
      columnName: "Description",
      filterComponentType: "valueFilter",
      maxLength: 20,
      showMaxLength: true,
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "CONFIRM_STATUS",
      columnName: "Confirm Status",
      filterComponentType: "valueFilter",
      maxLength: 20,
      showMaxLength: true,
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "TRAN_CD",
      isAutoSequence: true,
      columnName: "Sr. No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 70,
      maxWidth: 120,
    },
    {
      accessor: "DISP_MENU_FLAG",
      columnName: "Action Menu",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 70,
      maxWidth: 120,
    },
    {
      accessor: "DESCRIPTION",
      columnName: "Description",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "POPUP_STATUS",
      columnName: "Popup Status",
      sequence: 3,
      alignment: "left",
      componentType: "editableCheckbox",
      width: 108,
      minWidth: 80,
      maxWidth: 140,
      isReadOnly: true,
    },
    {
      accessor: "LOGIN_STATUS",
      columnName: "Login Status",
      sequence: 3,
      alignment: "left",
      componentType: "editableCheckbox",
      width: 105,
      minWidth: 80,
      maxWidth: 140,
      isReadOnly: true,
    },
    {
      accessor: "ACTIVE",
      columnName: "Active",
      sequence: 3,
      alignment: "left",
      componentType: "editableCheckbox",
      width: 70,
      minWidth: 50,
      maxWidth: 100,
      isReadOnly: true,
    },
    {
      accessor: "CONFIRM_STATUS",
      columnName: "Confirm Status",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "Entered By",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "ENTERED_DATE",
      columnName: "Entered Date",
      sequence: 7,
      alignment: "left",
      componentType: "date",
      dateFormat: "dd/MM/yyyy HH:mm:ss",
      width: 150,
      minWidth: 100,
      maxWidth: 400,
    },
    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Modified By",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "Modified Date",
      sequence: 9,
      alignment: "left",
      componentType: "date",
      dateFormat: "dd/MM/yyyy HH:mm:ss",
      width: 120,
      minWidth: 170,
      maxWidth: 200,
    },
  ],
};
