import { GridMetaDataType } from "components/dataTableStatic";

export const leavesmstgrid: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Leaves Master",
    rowIdColumn: "TRAN_CD",

    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },

    allowColumnReordering: true,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    containerHeight: { min: "69vh", max: "69vh" },
    pageSizes: [15, 20, 30],
    defaultPageSize: 15,
    isCusrsorFocused: true,
    allowFilter: true,
  },
  filters: [
    {
      accessor: "TEMPLATE_DESC",
      columnName: "Template",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],

  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr_no",
      sequence: 1,
      alignment: "right",
      componentType: "default",
      width: 90,
      minWidth: 60,
      maxWidth: 120,
      isAutoSequence: true,
    },
    // {
    //   accessor: "TRAN_CD",
    //   columnName: "Tran. ID",
    //   sequence: 1,
    //   alignment: "right",
    //   componentType: "default",
    //   width: 90,
    //   minWidth: 60,
    //   maxWidth: 120,
    // },
    {
      accessor: "TEMPLATE_DESC",
      columnName: "Template",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 180,
      minWidth: 150,
      maxWidth: 220,
    },
    {
      accessor: "ACTIVE",
      columnName: "Active",
      sequence: 3,
      alignment: "left",
      componentType: "editableCheckbox",
      isReadOnly: true,
      width: 90,
      minWidth: 60,
      maxWidth: 120,
    },
    {
      accessor: "DEACTIVE_DT",
      columnName: "Deactive Date",
      sequence: 4,
      alignment: "left",
      componentType: "date",
      width: 120,
      minWidth: 110,
      maxWidth: 150,
      dateFormat: "dd/MM/yyyy",
    },
    {
      accessor: "CONFIRMED_STATUS",
      columnName: "Confirm Status",
      sequence: 5,
      alignment: "center",
      componentType: "default",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "Entered By",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "ENTERED_DATE",
      columnName: "Entered Date",
      sequence: 7,
      alignment: "center",
      componentType: "date",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
      dateFormat: "dd/MM/yyyy HH:mm:ss",
    },
    {
      accessor: "MACHINE_NM",
      columnName: "Machine Name",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
    },

    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Last Entered By",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 110,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "Last Modified date",
      sequence: 10,
      alignment: "center",
      componentType: "date",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
      dateFormat: "dd/MM/yyyy HH:mm:ss",
    },
    {
      accessor: "LAST_MACHINE_NM",
      columnName: "Last Machine name",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 120,
      maxWidth: 200,
    },
  ],
};
