import { GridMetaDataType } from "components/dataTableStatic";

export const AuthenticationMetrixGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Corporate User Registration Entry",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    hideHeader: true,
    disableGroupBy: true,
    enablePagination: true,
    containerHeight: { min: "45vh", max: "45vh" },
    pageSizes: [15, 20, 30],
    defaultPageSize: 15,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr. No.",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
      isAutoSequence: true,
    },
    {
      accessor: "FROM_AMOUNT",
      columnName: "From Amount.",
      sequence: 7,
      alignment: "center",
      componentType: "editableNumberFormat",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "TO_AMOUNT",
      columnName: "To Amount",
      sequence: 8,
      alignment: "left",
      componentType: "editableNumberFormat",
      width: 160,
      minWidth: 120,
      maxWidth: 200,
    },

    {
      accessor: "AUTHORIZED_PERSON",
      columnName: "By Number of User",
      sequence: 9,
      alignment: "left",
      componentType: "editableNumberFormat",
      width: 220,
      minWidth: 150,
      maxWidth: 400,
    },
  ],
};

export const AuthenticationMetrixViewGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Corporate User Registration Entry",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    hideHeader: true,
    disableGroupBy: true,
    enablePagination: true,
    containerHeight: { min: "45vh", max: "45vh" },
    pageSizes: [15, 20, 30],
    defaultPageSize: 15,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr. No.",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
      isAutoSequence: true,
    },
    {
      accessor: "FROM_AMOUNT",
      columnName: "From Amount.",
      sequence: 7,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "TO_AMOUNT",
      columnName: "To Amount",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 120,
      maxWidth: 200,
    },

    {
      accessor: "AUTHORIZED_PERSON",
      columnName: "By Number of User",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 220,
      minWidth: 150,
      maxWidth: 400,
    },
  ],
};
