import { GridMetaDataType } from "components/dataTableStatic";
export const VirtualCardProdTypeGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Virtual Card Product Type Configuration",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 30, 50],
    defaultPageSize: 15,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: true,
    allowColumnHiding: true,
  },
  filters: [
    {
      accessor: "PRODUCT_TYPE",
      columnName: "Product Type",
      filterComponentType: "optionsFilter",
      filterProps: {
        // selectType: "multiple",
        options: [
          { label: "DEBIT CARD", value: "DEBIT CARD" },
          { label: "PREPAID CARD", value: "PREPAID CARD" },
        ],
      },
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "CARD_PRODUCT_BIN",
      columnName: "Card Product BIN",
      filterComponentType: "valueFilter",
      maxLength: 20,
      showMaxLength: true,
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "PRODUCT_ID",
      columnName: "Product ID",
      filterComponentType: "valueFilter",
      maxLength: 50,
      showMaxLength: true,
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "PRODUCT_NAME",
      columnName: "Product Name",
      filterComponentType: "valueFilter",
      maxLength: 100,
      showMaxLength: true,
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "sr_no",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 100,
      isAutoSequence: true,
      isColumnHidingDisabled: true,
    },
    {
      accessor: "PRODUCT_TYPE",
      columnName: "Product Type",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      isColumnHidingDisabled: true,
      width: 130,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "CARD_PRODUCT_BIN",
      columnName: "Card Product BIN",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      isColumnHidingDisabled: true,
      width: 140,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "PRODUCT_ID",
      columnName: "Product ID",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      isColumnHidingDisabled: true,
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "PRODUCT_NAME",
      columnName: "Product Name",
      isColumnHidingDisabled: true,
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 220,
      minWidth: 100,
      maxWidth: 500,
    },
    {
      accessor: "CONFIRM_STATUS",
      columnName: "Confirm Status",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "Entered By",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      isVisible: false,
      isTableHidden: true,
      width: 110,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "ENTERED_DATE",
      columnName: "Entered Date",
      sequence: 7,
      alignment: "left",
      componentType: "date",
      placeholder: "",
      isVisible: false,
      isTableHidden: true,
      width: 150,
      minWidth: 120,
      maxWidth: 200,
      dateFormat: "dd/MM/yyyy HH:mm:ss",
    },
    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Last Modified By",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 140,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "Last Modified Date",
      sequence: 9,
      alignment: "left",
      componentType: "date",
      placeholder: "",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
      dateFormat: "dd/MM/yyyy HH:mm:ss",
    },
    {
      accessor: "VERIFIED_BY",
      columnName: "Verified By",
      sequence: 10,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "VERIFIED_DATE",
      columnName: "Verified Date",
      sequence: 11,
      alignment: "left",
      componentType: "date",
      placeholder: "",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
      dateFormat: "dd/MM/yyyy HH:mm:ss",
    },
  ],
};
