import { GridMetaDataType } from "components/dataTableStatic";

export const MobileValidationTemplateGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "MS Properties Configuration",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 25, 50],
    defaultPageSize: 15,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: true,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: true,
    hiddenFlag: "_hidden",
  },
  filters: [
    {
      accessor: "APPLICATION_NAME",
      columnName: "Application Name",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "PROFILE_NM",
      columnName: "Profile Name",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "LABEL",
      columnName: "Label",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "id",
      columnName: "Sr. No.",
      sequence: 1,
      alignment: "rigth",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 120,
      isAutoSequence: true,
    },
    {
      accessor: "APPLICATION_NAME",
      columnName: "Application Name",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 250,
      minWidth: 150,
      maxWidth: 500,
    },
    {
      accessor: "PROFILE_NM",
      columnName: "Profile Name",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 160,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "LABEL",
      columnName: "Label",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 400,
      minWidth: 150,
      maxWidth: 450,
    },
  ],
};
