import { GridMetaDataType } from "components/dataTableStatic";

export const MsMonitoringDetailsGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "MS Instance Informations",
    rowIdColumn: "instanceId",
    defaultColumnConfig: {
      width: 600,
      maxWidth: 750,
      minWidth: 300,
    },
    enablePagination: true,
    pageSizes: [15, 25, 50],
    defaultPageSize: 15,
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    hideFooter: false,
    disableGroupBy: true,
    containerHeight: {
      min: "48vh",
      max: "68vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
    hiddenFlag: "_hidden",
  },
  columns: [
    {
      accessor: "id",
      columnName: "Sr. No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 120,
      isAutoSequence: true,
    },
    {
      accessor: "instanceId",
      columnName: "Instance ID",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 300,
      minWidth: 300,
      maxWidth: 500,
    },
    {
      accessor: "status",
      columnName: "Status",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 150,
      minWidth: 100,
      maxWidth: 250,
      color: (val: string) => (val === "UP" ? "green" : "red"),
    },
  ],
};
