import { GridMetaDataType } from "components/dataTableStatic";

export const MsMonitoringGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "MS Monitoring Master",
    rowIdColumn: "service",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 25, 50],
    defaultPageSize: 15,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: true,
    hiddenFlag: "_hidden",
  },
  columns: [
    {
      accessor: "id",
      columnName: "Sr. No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 120,
      isAutoSequence: true,
    },
    {
      accessor: "service",
      columnName: "Service ID",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 370,
      minWidth: 300,
      maxWidth: 550,
    },
    {
      accessor: "status",
      columnName: "Status",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 150,
      minWidth: 100,
      maxWidth: 250,
      color: (val: string) => (val === "UP" ? "green" : "red"),
    },
    // {
    //   accessor: "totalInstance",
    //   columnName: "Total Instance",
    //   sequence: 5,
    //   alignment: "left",
    //   componentType: "default",
    //   placeholder: "",
    //   width: 170,
    //   minWidth: 120,
    //   maxWidth: 300,
    // },
    {
      accessor: "ACTIVE_INSTANCE",
      columnName: "Active Instance",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 170,
      minWidth: 120,
      maxWidth: 300,
    },
  ],
};
