import { GridMetaDataType } from "components/dataTableStatic";

export const AppReviewGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Application Review User Master",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: false,
    pageSizes: [20, 30, 40],
    defaultPageSize: 20,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: false,
    isCusrsorFocused: true,
    hiddenFlag: "_hidden",
  },
  filters: [],
  columns: [
    {
      accessor: "id1",
      columnName: "Sr. No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 100,
      isAutoSequence: true,
    },
    {
      accessor: "TRAN_CD",
      columnName: "Login Name",
      isVisible: false,
      sequence: 2,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 120,
      minWidth: 120,
      maxWidth: 400,
    },
    {
      accessor: "USER_NAME",
      columnName: "Login Name",
      isVisible: false,
      sequence: 2,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 120,
      minWidth: 120,
      maxWidth: 400,
    },
    {
      accessor: "CUSTOM_USER_NM",
      columnName: "Test Login ID",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 140,
      minWidth: 120,
      maxWidth: 400,
      schemaValidation: {
        type: "string",
        rules: [{ name: "required", params: ["This field is required"] }],
      },
    },
    {
      accessor: "CUST_NAME",
      columnName: "Review Login Name",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 150,
      minWidth: 120,
      maxWidth: 400,
      schemaValidation: {
        type: "string",
        rules: [{ name: "required", params: ["This field is required"] }],
      },
    },
    {
      accessor: "APP_VERSION",
      columnName: "Latest Version",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      placeholder: "Enter Latest App Version",
      width: 150,
      minWidth: 100,
      maxWidth: 400,
      schemaValidation: {
        type: "string",
        rules: [{ name: "required", params: ["This field is required"] }],
      },
    },
    {
      accessor: "VALID_UPTO",
      columnName: "Expiry Date",
      sequence: 5,
      alignment: "left",
      componentType: "date",
      dateFormat: "dd/MM/yyyy HH:mm:ss",
      width: 150,
      minWidth: 150,
      maxWidth: 400,
    },
    {
      accessor: "LAST_LOGIN_DT",
      columnName: "Test User Last Login Date",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 190,
      minWidth: 190,
      maxWidth: 400,
    },
    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Modified By",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "Modified Date",
      sequence: 10,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy HH:mm:ss",
      width: 150,
      minWidth: 130,
      maxWidth: 170,
    },
    {
      accessor: "ACTIVE",
      columnName: "Active",
      sequence: 11,
      alignment: "center",
      componentType: "editableCheckbox",
      isReadOnly: true,
      width: 90,
      minWidth: 60,
      maxWidth: 120,
    },
  ],
};
