import { GridMetaDataType } from "components/dataTableStatic";
export const ServMobileValidGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Service wise Mobile Number Validation Template Mapping",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: true,
    allowColumnHiding: true,
    isCusrsorFocused: true,
  },
  filters: [
    {
      accessor: "SERVICE_NM",
      columnName: "Service Name",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr. No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 60,
      isVisible: true,
      maxWidth: 100,
      isAutoSequence: true,
    },

    {
      accessor: "SERVICE_NM",
      columnName: "Service Name",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 350,
      minWidth: 150,
      maxWidth: 400,
    },
    {
      accessor: "TRN_TYPE",
      columnName: "Service Name",
      sequence: 3,
      isVisible: false,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 150,
      maxWidth: 300,
    },
    {
      accessor: "MOB_TMPLT_TRAN_CD",
      columnName: "Service Name",
      sequence: 3,
      isVisible: false,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 150,
      maxWidth: 300,
    },

    {
      accessor: "TEMPLATE_NM",
      columnName: "Template Name",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 350,
      minWidth: 150,
      maxWidth: 400,
    },
    {
      accessor: "CONFIRMED_STATUS",
      columnName: "Confirm Status",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 150,
      maxWidth: 400,
    },
    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Modified By",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },

    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "Modified Date",
      sequence: 6,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy HH:mm:ss",
      width: 150,
      minWidth: 130,
      maxWidth: 170,
    },
  ],
};
