import { GridMetaDataType } from "components/dataTableStatic";

export const RootDevrepoGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Rooted Device Repository",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [10, 20, 30],
    defaultPageSize: 10,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: true,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: false,
  },
  filters: [
    {
      accessor: "DEVICE_ID",
      columnName: "Device ID",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "DEVICE_OS",
      columnName: "Device OS",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "DEVICE_NM",
      columnName: "Device Name",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "DEVICE_USER_NM",
      columnName: "Device User Name",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "DEVICE_IP",
      columnName: "Device IP",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "APP_VERSION",
      columnName: "App Version",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "DISP_STATUS",
      columnName: "Status",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "CONFIRM_STATUS",
      columnName: "Confirm Status",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "TRAN_CD",
      columnName: "Sr.No.",
      isVisible: false,
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "SR_NO",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 50,
      minWidth: 80,
      maxWidth: 150,
    },
    {
      accessor: "REQ_DATE",
      columnName: "Request Date",
      sequence: 1,
      alignment: "left",
      componentType: "date",
      width: 150,
      minWidth: 150,
      maxWidth: 200,
    },
    {
      accessor: "DEVICE_OS",
      columnName: "Device OS",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 150,
    },
    {
      accessor: "DEVICE_IMEI",
      columnName: "Device IMEI",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "DEVICE_NM",
      columnName: "Device Name",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 130,
      maxWidth: 230,
    },
    {
      accessor: "DEVICE_USER_NM",
      columnName: "Device User Name",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 130,
      maxWidth: 200,
    },
    {
      accessor: "DEVICE_ID",
      columnName: "Device ID",
      sequence: 6,
      alignment: "center",
      componentType: "default",
      //dateFormat: "dd/mm/yyyy",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },

    {
      accessor: "DEVICE_IP",
      columnName: "Device IP",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
    {
      accessor: "APP_VERSION",
      columnName: "App Version",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 100,
      minWidth: 80,
      maxWidth: 200,
    },
    {
      accessor: "DISP_STATUS",
      columnName: "Status",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 150,
      maxWidth: 300,
    },
    {
      accessor: "CONFIRM_STATUS",
      columnName: "Confirm Status",
      sequence: 10,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 150,
      maxWidth: 300,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "Maker",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "MAKER_REMARKS",
      columnName: "Maker Remark",
      sequence: 12,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "VERIFIED_BY",
      columnName: "Checker",
      sequence: 13,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "CHECKER_REMARKS",
      columnName: "Checker Remark",
      sequence: 14,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "DEVICE_MAC",
      columnName: "Maker",
      isVisible: false,
      sequence: 15,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "ALLOW_STATUS",
      columnName: "Maker",
      isVisible: false,
      sequence: 16,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "CONFIRMED",
      columnName: "Maker",
      isVisible: false,
      sequence: 17,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "ENTERED_DATE",
      columnName: "Maker",
      isVisible: false,
      sequence: 18,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "MACHINE_NM",
      columnName: "Maker",
      isVisible: false,
      sequence: 19,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "VERIFIED_DATE",
      columnName: "Maker",
      isVisible: false,
      sequence: 20,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "VERIFIED_MACHINE_NM",
      columnName: "Maker",
      isVisible: false,
      sequence: 21,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
  ],
};
