import { GridMetaDataType } from "components/dataTableStatic";

export const MsMessageConfigGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "MS Service Message Configuration",
    rowIdColumn: "SR_CD",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [20, 30, 50],
    defaultPageSize: 20,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: true,
    allowColumnHiding: true,
    isCusrsorFocused: true,
  },
  filters: [
    {
      accessor: "KEY_NM",
      columnName: "Key Name",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "DESCRIPTION",
      columnName: "Description",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
    {
      accessor: "MESSAGE_EN",
      columnName: "Default Message",
      filterComponentType: "valueFilter",
      gridProps: {
        xs: 12,
        md: 12,
        sm: 12,
      },
    },
  ],
  columns: [
    {
      accessor: "SR_CD",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 60,
      isVisible: true,
      maxWidth: 100,
      isAutoSequence: true,
    },

    {
      accessor: "KEY_NM",
      columnName: "Key Name",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 150,
      maxWidth: 400,
    },
    {
      accessor: "MESSAGE_EN",
      columnName: "Default Message",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 150,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "MESSAGE_BN",
      columnName: "Local Language Message",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      isVisible: false,
      width: 300,
      minWidth: 150,
      maxWidth: 400,
      showTooltip: true,
    },
    {
      accessor: "DISPL_LOCAL_LANG_MESS",
      columnName: "Local Language Message",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 300,
      minWidth: 150,
      maxWidth: 400,
      showTooltip: true,
    },

    {
      accessor: "DESCRIPTION",
      columnName: "Description",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      width: 200,

      minWidth: 150,
      maxWidth: 400,
    },

    {
      accessor: "ACTIVE",
      columnName: "Active",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 50,
      maxWidth: 200,
    },
    {
      accessor: "ORDER_BY",
      columnName: "Order by",
      sequence: 7,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 50,
      maxWidth: 170,
    },
    {
      accessor: "COMMENTS",
      columnName: "Comments",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 130,
      maxWidth: 170,
    },
    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Modified By",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "Modified Date",
      sequence: 10,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy HH:mm:ss",
      width: 150,
      minWidth: 130,
      maxWidth: 170,
    },
  ],
};
