import { GridMetaDataType } from "components/dataTableStatic";

export const AccountMappingGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Corporate User Registration Entry",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    hideHeader: true,
    disableGroupBy: true,
    enablePagination: true,
    containerHeight: { min: "45vh", max: "45vh" },
    pageSizes: [15, 20, 30],
    defaultPageSize: 15,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr. No.",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
      isAutoSequence: true,
    },
    {
      accessor: "REG_DATE",
      columnName: "Reg Date.",
      sequence: 7,
      alignment: "center",
      componentType: "editableDatePicker",
      dateFormat: "dd/MM/yyyy",
      width: 150,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "ACCOUNT_NO",
      columnName: "A/C. No.",
      sequence: 8,
      alignment: "left",
      componentType: "editableTextField",
      width: 160,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      columnName: "Sign",
      componentType: "buttonRowCell",
      accessor: "FILE_DATA",
      sequence: 9,
      buttonLabel: ". . .",
      width: 150,
      minWidth: 150,
      maxWidth: 150,
    },
    // {
    //   accessor: "SIGN",
    //   columnName: "Sign",
    //   sequence: 9,
    //   alignment: "left",
    //   componentType: "editableTextField",
    //   width: 220,
    //   minWidth: 150,
    //   maxWidth: 400,
    // },
    {
      accessor: "OWN_ACCOUNT",
      columnName: "Own A/C",
      sequence: 11,
      alignment: "left",
      componentType: "editableCheckbox",
      width: 100,
      minWidth: 50,
      maxWidth: 100,
    },
    {
      accessor: "OWN_LIMIT_AMMOUNT",
      columnName: "Sanction Amount",
      sequence: 11,
      alignment: "left",
      componentType: "editableNumberFormat",
      width: 140,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "IFT",
      columnName: "Within Bank",
      sequence: 11,
      alignment: "center",
      componentType: "editableCheckbox",
      width: 100,
      minWidth: 50,
      maxWidth: 100,
    },
    {
      accessor: "IFT_LIMIT_AMOUNT",
      columnName: "Sanction Amount",
      sequence: 11,
      alignment: "left",
      componentType: "editableNumberFormat",
      width: 140,
      minWidth: 120,
      maxWidth: 200,
    },

    {
      accessor: "NEFT",
      columnName: "EFT",
      sequence: 11,
      alignment: "left",
      componentType: "editableCheckbox",
      width: 100,
      minWidth: 50,
      maxWidth: 100,
    },
    {
      accessor: "NEFT_LIMIT_AMMOUNT",
      columnName: "Sanction Amount",
      sequence: 11,
      alignment: "left",
      componentType: "editableNumberFormat",
      width: 140,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "RTGS",
      columnName: "RTGS",
      sequence: 11,
      alignment: "center",
      componentType: "editableCheckbox",
      width: 100,
      minWidth: 50,
      maxWidth: 100,
    },
    {
      accessor: "RTGS_LIMIT_AMMOUNT",
      columnName: "Sanction Amount",
      sequence: 11,
      alignment: "left",
      componentType: "editableNumberFormat",
      width: 140,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "IMPS",
      columnName: "IMPS",
      sequence: 11,
      alignment: "left",
      componentType: "editableCheckbox",
      width: 100,
      minWidth: 50,
      maxWidth: 100,
    },
    {
      accessor: "IMPS_LIMIT_AMMOUNT",
      columnName: "Sanction Amount",
      sequence: 11,
      alignment: "left",
      componentType: "editableNumberFormat",
      width: 140,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "BBPS",
      columnName: "Utility Bill Payment",
      sequence: 11,
      alignment: "left",
      componentType: "editableCheckbox",
      width: 150,
      minWidth: 150,
      maxWidth: 300,
    },
    {
      accessor: "BBPS_LIMIT_AMMOUNT",
      columnName: "Sanction Amount",
      sequence: 11,
      alignment: "left",
      componentType: "editableNumberFormat",
      width: 140,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "PAYMENT",
      columnName: "Payment Getway",
      sequence: 11,
      alignment: "left",
      componentType: "editableCheckbox",
      width: 150,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "PAYMENT_LIMIT_AMMOUNT",
      columnName: "Sanction Amount",
      sequence: 11,
      alignment: "left",
      componentType: "editableNumberFormat",
      width: 140,
      minWidth: 120,
      maxWidth: 200,
    },
  ],
};

export const AccountMappingViewGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Corporate User Registration Entry",
    rowIdColumn: "SR_NO",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    hideHeader: true,
    disableGroupBy: true,
    enablePagination: true,
    containerHeight: { min: "40vh", max: "40vh" },
    pageSizes: [15, 20, 30],
    defaultPageSize: 15,
    allowRowSelection: false,
  },
  filters: [],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr. No.",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
      isAutoSequence: true,
    },
    {
      accessor: "REG_DATE",
      columnName: "Reg Date.",
      sequence: 7,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "ACCOUNT_NO",
      columnName: "A/C. No.",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 160,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      columnName: "Sign",
      componentType: "buttonRowCell",
      accessor: "FILE_DATA",
      sequence: 9,
      buttonLabel: ". . .",
      width: 150,
      minWidth: 150,
      maxWidth: 150,
    },
    // {
    //   accessor: "SIGN",
    //   columnName: "Sign",
    //   sequence: 9,
    //   alignment: "left",
    //   componentType: "editableTextField",
    //   width: 220,
    //   minWidth: 150,
    //   maxWidth: 400,
    // },
    {
      accessor: "OWN_ACCOUNT",
      columnName: "Own A/C",
      sequence: 11,
      alignment: "left",
      componentType: "editableCheckbox",
      width: 100,
      minWidth: 50,
      maxWidth: 100,
    },
    {
      accessor: "OWN_LIMIT_AMMOUNT",
      columnName: "Sanction Amount",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "IFT",
      columnName: "Within Bank",
      sequence: 11,
      alignment: "center",
      componentType: "editableCheckbox",
      width: 100,
      minWidth: 50,
      maxWidth: 100,
    },
    {
      accessor: "IFT_LIMIT_AMOUNT",
      columnName: "Sanction Amount",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 120,
      maxWidth: 200,
    },

    {
      accessor: "NEFT",
      columnName: "EFT",
      sequence: 11,
      alignment: "left",
      componentType: "editableCheckbox",
      width: 100,
      minWidth: 50,
      maxWidth: 100,
    },
    {
      accessor: "NEFT_LIMIT_AMMOUNT",
      columnName: "Sanction Amount",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "RTGS",
      columnName: "RTGS",
      sequence: 11,
      alignment: "center",
      componentType: "editableCheckbox",
      width: 100,
      minWidth: 50,
      maxWidth: 100,
    },
    {
      accessor: "RTGS_LIMIT_AMMOUNT",
      columnName: "Sanction Amount",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "IMPS",
      columnName: "IMPS",
      sequence: 11,
      alignment: "center",
      componentType: "editableCheckbox",
      width: 100,
      minWidth: 50,
      maxWidth: 100,
    },
    {
      accessor: "IMPS_LIMIT_AMMOUNT",
      columnName: "Sanction Amount",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "BBPS",
      columnName: "Utility Bill Payment",
      sequence: 11,
      alignment: "center",
      componentType: "editableCheckbox",
      width: 150,
      minWidth: 150,
      maxWidth: 300,
    },
    {
      accessor: "BBPS_LIMIT_AMMOUNT",
      columnName: "Sanction Amount",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "PAYMENT",
      columnName: "Payment Getway",
      sequence: 11,
      alignment: "left",
      componentType: "editableCheckbox",
      width: 150,
      minWidth: 100,
      maxWidth: 150,
    },
    {
      accessor: "PAYMENT_LIMIT_AMMOUNT",
      columnName: "Sanction Amount",
      sequence: 11,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 120,
      maxWidth: 200,
    },
  ],
};
