import { GridMetaDataType } from "components/dataTableStatic";

export const holidayGrid: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Holiday/Business Day Configuration",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    containerHeight: { min: "69vh", max: "69vh" },
    pageSizes: [15, 20, 30],
    defaultPageSize: 15,
    isCusrsorFocused: true,
  },
  filters: [],
  columns: [
    {
      accessor: "id",
      columnName: "Sr. No.",
      sequence: 1,
      alignment: "rigth",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 120,
      isAutoSequence: true,
    },
    {
      accessor: "START_DT",
      columnName: "start Date",
      sequence: 2,
      alignment: "left",
      componentType: "date",
      placeholder: "",
      width: 150,
      minWidth: 100,
      maxWidth: 250,
      dateFormat: "dd/MM/yyyy",
    },
    {
      accessor: "END_DT",
      columnName: "End Date",
      sequence: 3,
      alignment: "left",
      componentType: "date",
      placeholder: "",
      width: 150,
      minWidth: 100,
      maxWidth: 250,
      dateFormat: "dd/MM/yyyy",
    },
    {
      accessor: "DESCRIPTION",
      columnName: "Description",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 150,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "Entered By",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 150,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "ENTERED_DATE",
      columnName: "Entered Date",
      sequence: 7,
      alignment: "left",
      componentType: "date",
      placeholder: "",
      width: 150,
      minWidth: 100,
      maxWidth: 250,
      dateFormat: "dd/MM/yyyy HH:mm:ss",
    },
    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "Last Enterd Date",
      sequence: 8,
      alignment: "left",
      componentType: "date",
      placeholder: "",
      width: 150,
      minWidth: 100,
      maxWidth: 250,
      dateFormat: "dd/MM/yyyy HH:mm:ss",
    },
  ],
};
