import { getChargeAllow, GetChargeTemplates } from "./api";

export const FromSourceMetaData = {
  form: {
    name: "12300006",
    label: "",
    validationRun: "onChange",
    render: {
      renderType: "tabs",
      groups: {
        "0": "Finacle As From Source",
        "1": "Ababil As From Source",
        "2": "Tranzware As From Source",
      },
      ordering: "sequence",
    },
  },
  fields: [
    {
      render: {
        componentType: "hidden",
        group: 0,
      },
      name: "TRAN_CD_0",
    },
    {
      render: {
        componentType: "hidden",
        group: 0,
      },
      name: "SR_CD_0",
    },
    {
      render: {
        componentType: "hidden",
        group: 0,
      },
      name: "APP_INDICATOR_0",
    },
    {
      render: {
        componentType: "hidden",
        group: 1,
      },
      name: "TRAN_CD_1",
    },
    {
      render: {
        componentType: "hidden",
        group: 1,
      },
      name: "SR_CD_1",
    },
    {
      render: {
        componentType: "hidden",
        group: 1,
      },
      name: "APP_INDICATOR_1",
    },
    {
      render: {
        componentType: "hidden",
        group: 2,
      },
      name: "TRAN_CD_2",
    },
    {
      render: {
        componentType: "hidden",
        group: 2,
      },
      name: "SR_CD_2",
    },
    {
      render: {
        componentType: "hidden",
        group: 2,
      },
      name: "APP_INDICATOR_2",
    },
    {
      render: { componentType: "select", group: 0 },
      name: "CHARGE_ALLOW_0",
      sequence: 1,
      label: "Charge",
      placeholder: "",
      defaultOptionLabel: "Charge",
      defaultValue: "",
      GridProps: { xs: 12, md: 3, sm: 3 },
      fullWidth: true,
      required: true,
      validate: "getValidateValue",
      disableCaching: true,
      options: () => getChargeAllow(),
      _optionsKey: "getChargeAllow",
    },
    {
      render: { componentType: "autocomplete", group: 0 },
      name: "CHRG_TEMP_TRAN_CD_0",
      sequence: 2,
      label: "Service Charge Template",
      placeholder: "Select Service Charge Template",
      GridProps: { xs: 12, md: 3, sm: 3 },
      fullWidth: true,
      disableCaching: true,
      options: () => GetChargeTemplates(),
      _optionsKey: "GetChargeTemplates",
    },
    {
      render: { componentType: "accountNumber", group: 0 },
      name: "SERV_TAX_ACCT_NO_0",
      sequence: 3,
      label: "Service Charge Account",
      placeholder: "Enter Service Charge Account",
      autoComplete: "off",
      defaultValue: "",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
      runValidationOnDependentFieldsChange: true,
      dependentFields: ["CHARGE_ALLOW_0"],
      validate: (currentField, dependentFields) => {
        if (
          dependentFields?.CHARGE_ALLOW_0?.value === "Y" &&
          !currentField?.value
        ) {
          return "This field is required";
        } else {
          return "";
        }
      },
    },
    {
      render: { componentType: "accountNumber", group: 0 },
      name: "VAT_ACCT_NO_0",
      sequence: 4,
      label: "VAT Account",
      placeholder: "Enter VAT Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
      runValidationOnDependentFieldsChange: true,
      dependentFields: ["CHARGE_ALLOW_0"],
      validate: (currentField, dependentFields) => {
        if (
          dependentFields?.CHARGE_ALLOW_0?.value === "Y" &&
          !currentField?.value
        ) {
          return "This field is required";
        } else {
          return "";
        }
      },
    },
    {
      render: { componentType: "formbutton", group: 0 },
      name: "TRAN_PARTICULARS_BTN_0",
      sequence: 4,
      label: "Transaction Particulars",
      maxLength: 20,
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "accountNumber", group: 0 },
      name: "SUSPENSE_CR_ACCT_NO_0",
      sequence: 5,
      label: "Finacle Suspense Credit Account",
      placeholder: "Enter Finacle Suspense Credit Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "accountNumber", group: 0 },
      name: "SUSPENSE_DR_ACCT_NO_0",
      sequence: 6,
      label: "Finacle Suspense Debit Account",
      placeholder: "Enter Finacle Suspense Debit Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "accountNumber", group: 0 },
      name: "ABABIL_SUS_CR_AC_NO_0",
      sequence: 7,
      label: "Ababil Suspense Credit Account",
      placeholder: "Enter Ababil Suspense Credit Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "accountNumber", group: 0 },
      name: "ABABIL_SUS_DR_AC_NO_0",
      sequence: 8,
      label: "Ababil Suspense Debit Account",
      placeholder: "Enter Ababil Suspense Debit Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "accountNumber", group: 0 },
      name: "CARD_SUS_CR_AC_NO_0",
      sequence: 9,
      label: "Card Suspense Credit Account",
      placeholder: "Enter Card Suspense Credit Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "accountNumber", group: 0 },
      name: "CARD_SUS_DR_AC_NO_0",
      sequence: 10,
      label: "Card Suspense Debit Account",
      placeholder: "Enter Card Suspense Debit Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },

    {
      render: { componentType: "select", group: 1 },
      name: "CHARGE_ALLOW_1",
      sequence: 1,
      label: "Charge",
      placeholder: "",
      defaultOptionLabel: "Charge",
      defaultValue: "",
      GridProps: { xs: 12, md: 3, sm: 3 },
      fullWidth: true,
      required: true,
      autoComplete: "off",
      validate: "getValidateValue",
      disableCaching: true,
      options: () => getChargeAllow(),
      _optionsKey: "getChargeAllow",
    },
    {
      render: { componentType: "autocomplete", group: 1 },
      name: "CHRG_TEMP_TRAN_CD_1",
      sequence: 2,
      label: "Service Charge Template",
      placeholder: "Select Service Charge Template",
      GridProps: { xs: 12, md: 3, sm: 3 },
      fullWidth: true,
      autoComplete: "off",
      disableCaching: true,
      options: () => GetChargeTemplates(),
      _optionsKey: "GetChargeTemplates",
    },
    {
      render: { componentType: "accountNumber", group: 1 },
      name: "SERV_TAX_ACCT_NO_1",
      sequence: 3,
      label: "Service Charge Account",
      placeholder: "Enter Service Charge Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "accountNumber", group: 1 },
      name: "VAT_ACCT_NO_1",
      sequence: 4,
      label: "VAT Account",
      placeholder: "Enter VAT Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "formbutton", group: 1 },
      name: "TRAN_PARTICULARS_BTN_1",
      sequence: 4,
      label: "Transaction Particulars",
      maxLength: 20,
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "accountNumber", group: 1 },
      name: "SUSPENSE_CR_ACCT_NO_1",
      sequence: 5,
      label: "Finacle Suspense Credit Account",
      placeholder: "Enter Finacle Suspense Credit Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "accountNumber", group: 1 },
      name: "SUSPENSE_DR_ACCT_NO_1",
      sequence: 6,
      label: "Finacle Suspense Debit Account",
      placeholder: "Enter Finacle Suspense Debit Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "accountNumber", group: 1 },
      name: "ABABIL_SUS_CR_AC_NO_1",
      sequence: 7,
      label: "Ababil Suspense Credit Account",
      placeholder: "Enter Ababil Suspense Credit Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "accountNumber", group: 1 },
      name: "ABABIL_SUS_DR_AC_NO_1",
      sequence: 8,
      label: "Ababil Suspense Debit Account",
      placeholder: "Enter Ababil Suspense Debit Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "accountNumber", group: 1 },
      name: "CARD_SUS_CR_AC_NO_1",
      sequence: 9,
      label: "Card Suspense Credit Account",
      placeholder: "Enter Card Suspense Credit Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "accountNumber", group: 1 },
      name: "CARD_SUS_DR_AC_NO_1",
      sequence: 10,
      label: "Card Suspense Debit Account",
      placeholder: "Enter Card Suspense Debit Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "select", group: 2 },
      name: "CHARGE_ALLOW_2",
      sequence: 1,
      label: "Charge",
      placeholder: "",
      defaultOptionLabel: "Charge",
      defaultValue: "",
      GridProps: { xs: 12, md: 3, sm: 3 },
      fullWidth: true,
      required: true,
      validate: "getValidateValue",
      disableCaching: true,
      options: () => getChargeAllow(),
      _optionsKey: "getChargeAllow",
    },
    {
      render: { componentType: "autocomplete", group: 2 },
      name: "CHRG_TEMP_TRAN_CD_2",
      sequence: 2,
      label: "Service Charge Template",
      placeholder: "Select Service Charge Template",
      GridProps: { xs: 12, md: 3, sm: 3 },
      fullWidth: true,
      disableCaching: true,
      options: () => GetChargeTemplates(),
      _optionsKey: "GetChargeTemplates",
    },
    {
      render: { componentType: "accountNumber", group: 2 },
      name: "SERV_TAX_ACCT_NO_2",
      sequence: 3,
      label: "Service Charge Account",
      placeholder: "Enter Service Charge Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "accountNumber", group: 2 },
      name: "VAT_ACCT_NO_2",
      sequence: 4,
      label: "VAT Account",
      placeholder: "Enter VAT Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "formbutton", group: 2 },
      name: "TRAN_PARTICULARS_BTN_2",
      sequence: 4,
      label: "Transaction Particulars",
      maxLength: 20,
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "accountNumber", group: 2 },
      name: "SUSPENSE_CR_ACCT_NO_2",
      sequence: 5,
      label: "Finacle Suspense Credit Account",
      placeholder: "Enter Finacle Suspense Credit Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "accountNumber", group: 2 },
      name: "SUSPENSE_DR_ACCT_NO_2",
      sequence: 6,
      label: "Finacle Suspense Debit Account",
      placeholder: "Enter Finacle Suspense Debit Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "accountNumber", group: 2 },
      name: "ABABIL_SUS_CR_AC_NO_2",
      sequence: 7,
      label: "Ababil Suspense Credit Account",
      placeholder: "Enter Ababil Suspense Credit Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "accountNumber", group: 2 },
      name: "ABABIL_SUS_DR_AC_NO_2",
      sequence: 8,
      label: "Ababil Suspense Debit Account",
      placeholder: "Enter Ababil Suspense Debit Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "accountNumber", group: 2 },
      name: "CARD_SUS_CR_AC_NO_2",
      sequence: 9,
      label: "Card Suspense Credit Account",
      placeholder: "Enter Card Suspense Credit Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: { componentType: "accountNumber", group: 2 },
      name: "CARD_SUS_DR_AC_NO_2",
      sequence: 10,
      label: "Card Suspense Debit Account",
      placeholder: "Enter Card Suspense Debit Account",
      defaultValue: "",
      autoComplete: "off",
      GridProps: { xs: 12, md: 2, sm: 2 },
      fullWidth: true,
      __VIEW__: { isReadOnly: true },
      __EDIT__: { isReadOnly: false },
    },
    {
      render: {
        componentType: "hidden",
        group: 0,
      },
      name: "TRN_PERTICULERS_0",
    },
    {
      render: {
        componentType: "hidden",
        group: 0,
      },
      name: "TRN_PERTICULERS2_0",
    },
    {
      render: {
        componentType: "hidden",
        group: 0,
      },
      name: "ABABIL_TRN_PERTICULERS_0",
    },
    {
      render: {
        componentType: "hidden",
        group: 0,
      },
      name: "ABABIL_TRN_PERTICULERS2_0",
    },
    {
      render: {
        componentType: "hidden",
        group: 0,
      },
      name: "TRANZWARE_TRN_PERTICULERS_0",
    },
    {
      render: {
        componentType: "hidden",
        group: 0,
      },
      name: "TRANZWARE_TRN_PERTICULERS2_0",
    },
    {
      render: {
        componentType: "hidden",
        group: 1,
      },
      name: "TRN_PERTICULERS_1",
    },
    {
      render: {
        componentType: "hidden",
        group: 1,
      },
      name: "TRN_PERTICULERS2_1",
    },
    {
      render: {
        componentType: "hidden",
        group: 1,
      },
      name: "ABABIL_TRN_PERTICULERS_1",
    },
    {
      render: {
        componentType: "hidden",
        group: 1,
      },
      name: "ABABIL_TRN_PERTICULERS2_1",
    },
    {
      render: {
        componentType: "hidden",
        group: 1,
      },
      name: "TRANZWARE_TRN_PERTICULERS_1",
    },
    {
      render: {
        componentType: "hidden",
        group: 1,
      },
      name: "TRANZWARE_TRN_PERTICULERS2_1",
    },
    {
      render: {
        componentType: "hidden",
        group: 2,
      },
      name: "TRN_PERTICULERS_2",
    },
    {
      render: {
        componentType: "hidden",
        group: 2,
      },
      name: "TRN_PERTICULERS2_2",
    },
    {
      render: {
        componentType: "hidden",
        group: 2,
      },
      name: "ABABIL_TRN_PERTICULERS_2",
    },
    {
      render: {
        componentType: "hidden",
        group: 2,
      },
      name: "ABABIL_TRN_PERTICULERS2_2",
    },
    {
      render: {
        componentType: "hidden",
        group: 2,
      },
      name: "TRANZWARE_TRN_PERTICULERS_2",
    },
    {
      render: {
        componentType: "hidden",
        group: 2,
      },
      name: "TRANZWARE_TRN_PERTICULERS2_2",
    },
  ],
};
