import { GridMetaDataType } from "components/dataTableStatic";

export const MsUpdateServicesGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Properties List",
    rowIdColumn: "value",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    enablePagination: true,
    pageSizes: [15, 25, 50],
    defaultPageSize: 15,
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    hideFooter: false,
    disableGroupBy: true,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: true,
    hiddenFlag: "_hidden",
  },
  columns: [
    {
      accessor: "id",
      columnName: "Sr. No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 120,
      isAutoSequence: true,
    },
    {
      accessor: "value",
      columnName: "Properties",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 350,
      minWidth: 300,
      maxWidth: 550,
    },
    {
      accessor: "label",
      columnName: "Description",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 350,
      minWidth: 300,
      maxWidth: 550,
    },
  ],
};
