import { GridMetaDataType } from "components/dataTableStatic";

export const MicroServiceListGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Micro Service List",
    rowIdColumn: "SERVICE",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    enablePagination: true,
    pageSizes: [15, 25, 50],
    defaultPageSize: 15,
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    hideFooter: false,
    disableGroupBy: true,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: false,
    isCusrsorFocused: true,
    hiddenFlag: "_hidden",
  },
  columns: [
    {
      accessor: "id",
      columnName: "Sr. No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 120,
      isAutoSequence: true,
    },
    {
      accessor: "SERVICE",
      columnName: "Service ID",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 250,
      minWidth: 250,
      maxWidth: 550,
    },
    {
      accessor: "INSTANCE_ID",
      columnName: "Instance ID",
      sequence: 3,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 200,
      minWidth: 150,
      maxWidth: 300,
    },
    {
      accessor: "INSTANCE_STATUS",
      columnName: "Instance Status",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
      color: (val) => (val === "UP" ? "green" : "red"),
    },
    {
      accessor: "UPD_STATUS",
      columnName: "Update Status",
      sequence: 5,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 120,
      minWidth: 100,
      maxWidth: 200,
      color: (val) => (val.toLowerCase().includes("success") ? "green" : "red"),
    },
    {
      accessor: "RESPONSE",
      columnName: "API Response",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 500,
      minWidth: 400,
      maxWidth: 900,
    },
  ],
};
