import { components } from "components/report";

export const creditCardPaymentDetail = {
  title: "Credit Card Payment Report",
  disableGroupBy: "",
  hideFooter: "",
  hideAmountIn: "False",
  retrievalType: "CREDITTRAN",
  autoFetch: false,
  // filters: [
  //   {
  //     accessor: "FROM_DT",
  //     columnName: "From Date",
  //     filterComponentType: "valueDateFilter",
  //     gridProps: {
  //       xs: 12,
  //       md: 12,
  //       sm: 12,
  //     },
  //   },
  //   {
  //     accessor: "TO_DT",
  //     columnName: "To Date",
  //     filterComponentType: "valueDateFilter",
  //     gridProps: {
  //       xs: 12,
  //       md: 12,
  //       sm: 12,
  //     },
  //   },
  // ],
  columns: [
    {
      columnName: "Transaction Date",
      accessor: "TRAN_DT",
      width: 160,
      Cell: components.DateTimeCell,
      type: "default",
    },
    {
      columnName: "Reference No",
      accessor: "REF_NO",
      width: 140,
      type: "default",
    },
    {
      columnName: "Login ID",
      accessor: "USER_NAME",
      width: 140,
      type: "default",
    },
    {
      columnName: "Transaction Type",
      accessor: "TRN_TYPE",
      width: 170,
      type: "default",
    },
    {
      columnName: "Amount",
      accessor: "AMOUNT",
      width: 140,
      type: "default",
      isDisplayTotal: true,
      Cell: components.NumberCell,
      alignment: "right",
    },
    {
      columnName: "Charge Amount",
      accessor: "SERVICE_CHARGE",
      width: 160,
      type: "default",
      isDisplayTotal: true,
      Cell: components.NumberCell,
      alignment: "right",
    },
    {
      columnName: "VAT Amount",
      accessor: "VAT_CHARGE",
      width: 160,
      type: "default",
      isDisplayTotal: true,
      Cell: components.NumberCell,
      alignment: "right",
    },
    {
      columnName: "From Source",
      accessor: "FROM_SOURCE",
      width: 140,
      type: "default",
    },
    {
      columnName: "CB Number",
      accessor: "APP_CUSTOMER_ID",
      width: 140,
      type: "default",
    },
    {
      columnName: "From A/C Number",
      accessor: "FROM_ACCT_NO",
      width: 160,
      type: "default",
    },
    {
      columnName: "To Card No.",
      accessor: "CARD_NO",
      width: 140,
      type: "default",
    },
    {
      columnName: "Recipient name",
      accessor: "RECIPIENT_NAME",
      width: 170,
      type: "default",
    },
    {
      columnName: "Mobile No.",
      accessor: "MOBILE_NO",
      width: 140,
      type: "default",
    },
    {
      columnName: "Recipient Email",
      accessor: "RECIPIENT_EMAIL",
      width: 170,
      type: "default",
    },
    {
      columnName: "Status",
      accessor: "TRN_STATUS",
      width: 140,
      type: "default",
    },
    {
      columnName: "Process Date",
      accessor: "PROCESS_DT",
      width: 170,
      Cell: components.DateTimeCell,
      type: "default",
    },
    {
      columnName: "Curr Code",
      accessor: "CURR_CODE",
      width: 140,
      type: "default",
    },
    {
      columnName: "To Curr Code",
      accessor: "TO_CURR_CODE",
      width: 140,
      type: "default",
    },
    {
      columnName: "Curr Int.",
      accessor: "CURR_RATE",
      width: 140,
      type: "default",
    },
    {
      columnName: "Card Type",
      accessor: "CARD_TYPE",
      width: 140,
      type: "default",
    },
    {
      columnName: "Payment Type",
      accessor: "PAYMENT_TYPE",
      width: 140,
      type: "default",
    },
    {
      columnName: "Form Email ID",
      accessor: "EMAIL_ID",
      width: 150,
    },
    {
      columnName: "OTP Type",
      accessor: "OTP_TYPE",
      width: 150,
    },
    {
      columnName: "Remarks",
      accessor: "REMARKS",
      width: 150,
    },
    {
      columnName: "API Response",
      accessor: "API_RESPONSE",
      width: 150,
      Cell: components.ButtonRowCell,
      type: "default",
    },
    {
      columnName: "Trn. Particulars",
      accessor: "TRN_PARTICULARS",
      width: 160,
      Cell: components.ButtonRowCell,
      type: "default",
    },
  ],
};
