import { components } from "components/report";
export const fundTrfDetailsMetaData = {
  title: "Fund Transfer Transaction Details",
  disableGroupBy: "",
  hideFooter: "",
  hideAmountIn: "False",
  retrievalType: "FUNDTRAN",
  enableServerSidePagination: true,
  autoFetch: false,
  columns: [
    {
      columnName: "Transaction Date",
      accessor: "TRAN_DT",
      width: 160,
      Cell: components.DateTimeCell,
      type: "default",
    },
    {
      columnName: "Login ID",
      accessor: "USER_NAME",
      width: 140,
      type: "default",
    },
    {
      columnName: "Transaction Type",
      accessor: "TRN_TYPE",
      width: 180,
    },
    {
      columnName: "Amount",
      accessor: "AMOUNT",
      width: 150,
      isDisplayTotal: true,
      Cell: components.NumberCell,
      alignment: "right",
    },
    {
      columnName: "Charge Amount",
      accessor: "SERVICE_CHARGE",
      width: 150,
      isDisplayTotal: true,
      Cell: components.NumberCell,
      alignment: "right",
    },
    {
      columnName: "VAT Amount",
      accessor: "VAT_CHARGE",
      width: 150,
      isDisplayTotal: true,
      Cell: components.NumberCell,
      alignment: "right",
    },
    {
      columnName: "From Source",
      accessor: "APP_INDICATOR",
      width: 140,
    },
    {
      columnName: "CB Number",
      accessor: "APP_CUSTOMER_ID",
      width: 140,
    },
    {
      columnName: "From A/C No.",
      accessor: "FROM_ACCT_NO",
      width: 150,
    },
    {
      columnName: "From A/C Name.",
      accessor: "FROM_ACCT_NM",
      width: 160,
    },
    {
      columnName: "To A/C No.",
      accessor: "TO_ACCT_NO",
      width: 150,
    },
    {
      columnName: "To A/C Name.",
      accessor: "TO_ACCT_NM",
      width: 170,
    },
    {
      columnName: "To IFSC Code",
      accessor: "TO_IFSCCODE",
      width: 140,
    },
    {
      columnName: "Bank Name",
      accessor: "BANK_NM",
      width: 180,
    },
    {
      columnName: "Branch Name",
      accessor: "BRANCH_NM",
      width: 180,
    },
    {
      columnName: "Status",
      accessor: "TRN_STATUS",
      width: 130,
    },
    {
      columnName: "Process Date",
      accessor: "PROCESS_DT",
      width: 160,
      Cell: components.DateTimeCell,
      type: "default",
    },
    {
      columnName: "Ref No.",
      accessor: "REF_NO",
      width: 150,
    },
    {
      columnName: "OTP Type",
      accessor: "OTP_TYPE",
      width: 120,
    },
    {
      columnName: "From Contact No.",
      accessor: "MOBILE_NO",
      width: 160,
    },
    {
      columnName: "From Email ID",
      accessor: "EMAIL_ID",
      width: 180,
    },
    {
      columnName: "To Contact No.",
      accessor: "TO_CONTACT_NO",
      width: 160,
    },
    {
      columnName: "To Email ID",
      accessor: "TO_EMAIL_ID",
      width: 180,
    },
    {
      columnName: "Trans. Flow",
      accessor: "REQ_TYPE",
      width: 150,
    },
    {
      columnName: "Nick Name",
      accessor: "NICK_NAME",
      width: 150,
    },
    {
      columnName: "Remarks",
      accessor: "REMARKS",
      width: 150,
    },
    {
      columnName: "API Response",
      accessor: "API_RESPONSE",
      width: 150,
      Cell: components.ButtonRowCell,
      type: "default",
    },
    {
      columnName: "Trn. Particulars",
      accessor: "TRN_PARTICULARS",
      width: 160,
      Cell: components.ButtonRowCell,
      type: "default",
    },
  ],
};
