import { components } from "components/report";

export const utilityBillerPaymentMetaData = {
  title: "Utility Bill Payment Report",
  disableGroupBy: "",
  hideFooter: "",
  hideAmountIn: "False",
  retrievalType: "UTILITY",
  autoFetch: false,
  // groupBy: ["CATEGORY_ID", "CATEGORY_NAME", "BILLER_ID", "BILLER_NAME"],
  columns: [
    {
      columnName: "Ref. No.",
      accessor: "REF_NO",
      width: 140,
      type: "default",
    },
    {
      columnName: "Transaction Date",
      accessor: "TRAN_DT",
      width: 160,
      Cell: components.DateTimeCell,
      type: "default",
    },
    {
      columnName: "Login ID",
      accessor: "USER_NAME",
      width: 140,
      type: "default",
    },
    {
      columnName: "From Source.",
      accessor: "FROM_SOURCE",
      width: 140,
    },
    {
      columnName: "From Account",
      accessor: "FROM_ACCT_NO",
      width: 150,
    },
    {
      columnName: "Bill Number",
      accessor: "BILL_NO",
      width: 160,
    },
    {
      columnName: "Category ID",
      accessor: "CATEGORY_ID",
      width: 160,
    },
    {
      columnName: "Category Name",
      accessor: "CATEGORY_NAME",
      width: 160,
    },
    {
      columnName: "Biller ID",
      accessor: "BILLER_ID",
      width: 160,
    },
    {
      columnName: "Biller Name",
      accessor: "BILLER_NAME",
      width: 160,
    },
    {
      columnName: "Amount",
      accessor: "AMOUNT",
      width: 160,
      isDisplayTotal: true,
      Cell: components.NumberCell,
      alignment: "right",
    },
    {
      columnName: "Service Charge",
      accessor: "SERVICE_CHARGE",
      width: 160,
      isDisplayTotal: true,
      Cell: components.NumberCell,
      alignment: "right",
    },
    {
      columnName: "VAT",
      accessor: "VAT",
      width: 160,
      isDisplayTotal: true,
      Cell: components.NumberCell,
      alignment: "right",
    },
    {
      columnName: "Grand Total",
      accessor: "TOTAL_AMT",
      width: 160,
      isDisplayTotal: true,
      Cell: components.NumberCell,
      alignment: "right",
    },
    {
      columnName: "Channel",
      accessor: "CHANNEL",
      width: 110,
    },
    {
      columnName: "Status",
      accessor: "STATUS",
      width: 110,
    },
    {
      columnName: "OTP Type",
      accessor: "OTP_TYPE",
      width: 110,
    },
    {
      columnName: "OTP Mobile No.",
      accessor: "OTP_MOBILE",
      width: 160,
    },
    {
      columnName: "OTP Email ID",
      accessor: "OTP_EMAIL",
      width: 200,
    },
    {
      columnName: "Transaction Ref. ID",
      accessor: "TRANSACTION_REF_NO",
      width: 160,
      type: "default",
    },
    {
      columnName: "Other Details",
      accessor: "OTHER_DETAILS",
      width: 200,
    },
    {
      columnName: "API Response",
      accessor: "API_RESPONSE",
      width: 150,
      Cell: components.ButtonRowCell,
      type: "default",
    },
    {
      columnName: "Trn. Particulars",
      accessor: "TRN_PARTICULARS",
      width: 160,
      Cell: components.ButtonRowCell,
      type: "default",
    },
  ],
};
