import { GridMetaDataType } from "components/dataTableStatic";

export const TenureTypeConfigGridMetaData: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Tenure Type Configuration",
    rowIdColumn: "TRAN_CD",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    disableSorting: false,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    pageSizes: [15, 25, 50],
    defaultPageSize: 15,
    containerHeight: {
      min: "68vh",
      max: "68vh",
    },
    allowFilter: false,
    allowColumnHiding: false,
    allowRowSelection: true,
    isCusrsorFocused: true,
    hiddenFlag: "_hidden",
  },
  filters: [],
  columns: [
    {
      accessor: "id",
      columnName: "Sr.No.",
      sequence: 1,
      alignment: "rigth",
      componentType: "default",
      width: 70,
      minWidth: 60,
      maxWidth: 120,
      isAutoSequence: true,
    },
    {
      accessor: "TRN_TYPE",
      columnName: "Transaction Type",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 140,
      minWidth: 120,
      maxWidth: 180,
    },

    {
      accessor: "ACCT_TYPE",
      columnName: "Account Type",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 150,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "TRN_TYPE_DISPLAY",
      columnName: "Transaction Type Display",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 200,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      accessor: "ACCT_TYPE_DISPLAY",
      columnName: "Account Type Display",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      placeholder: "",
      width: 200,
      minWidth: 100,
      maxWidth: 250,
    },

    {
      accessor: "TRAN_CD",
      columnName: "Id",
      isVisible: false,
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 200,
      minWidth: 150,
      maxWidth: 400,
    },
    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Modified By",
      sequence: 8,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 140,
      maxWidth: 180,
    },
    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "Modified Date",
      sequence: 9,
      alignment: "center",
      componentType: "date",
      dateFormat: "dd/MM/yyyy",
      width: 120,
      minWidth: 120,
      maxWidth: 150,
    },
  ],
};
