import { GridMetaDataType } from "components/dataTableStatic";

export const productnamedata: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Product Display Name Configuration",
    rowIdColumn: "SR_NO",

    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    containerHeight: { min: "57vh", max: "57vh" },
    pageSizes: [15, 20, 30],
    defaultPageSize: 15,
    isCusrsorFocused: true,
  },
  filters: [],

  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr. No.",
      sequence: 1,
      alignment: "right",
      componentType: "default",
      width: 90,
      minWidth: 60,
      maxWidth: 120,
      isAutoSequence: true,
    },
    {
      accessor: "PROD_DISPL_NAME",
      columnName: "Display Name",
      sequence: 2,
      alignment: "left",
      componentType: "default",
      width: 220,
      minWidth: 150,
      maxWidth: 240,
    },
    {
      accessor: "ACTIVE",
      columnName: "Active",
      sequence: 3,
      alignment: "left",
      componentType: "editableCheckbox",
      isReadOnly: true,
      width: 90,
      minWidth: 60,
      maxWidth: 120,
    },
    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Modified By",
      sequence: 4,
      alignment: "left",
      componentType: "default",
      width: 150,
      minWidth: 140,
      maxWidth: 160,
    },
    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "Last Entered date",
      sequence: 5,
      alignment: "right",
      componentType: "date",
      width: 150,
      minWidth: 140,
      maxWidth: 160,
      dateFormat: "dd/MM/yyyy HH:mm:ss",
    },
  ],
};
