import { GridMetaDataType } from "components/dataTableStatic";

export const corporateUserRegistration: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Corporate User Registration Entry",
    rowIdColumn: "CUSTOMER_ID",
    defaultColumnConfig: {
      width: 400,
      maxWidth: 450,
      minWidth: 300,
    },
    allowColumnReordering: true,
    hideHeader: false,
    disableGroupBy: true,
    enablePagination: true,
    containerHeight: { min: "70vh", max: "70vh" },
    pageSizes: [15, 20, 30],
    defaultPageSize: 15,
  },
  filters: [],
  columns: [
    {
      accessor: "SR_NO",
      columnName: "Sr. No.",
      sequence: 1,
      alignment: "left",
      componentType: "default",
      width: 80,
      minWidth: 70,
      maxWidth: 120,
      isAutoSequence: true,
    },
    {
      accessor: "CUSTOMER_ID",
      columnName: "Customer ID",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "DOMAIN_NM",
      columnName: "Domain Name",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "NAME",
      columnName: "Name",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 220,
      minWidth: 120,
      maxWidth: 400,
    },
    {
      accessor: "ENTERED_BY",
      columnName: "Entered By",
      sequence: 6,
      alignment: "left",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "ENTERED_DATE",
      columnName: "Entered date",
      sequence: 7,
      alignment: "center",
      componentType: "default",
      width: 120,
      minWidth: 120,
      maxWidth: 200,
    },
    {
      accessor: "LAST_ENTERED_BY",
      columnName: "Last Entered By",
      sequence: 9,
      alignment: "left",
      componentType: "default",
      width: 130,
      minWidth: 150,
      maxWidth: 200,
    },
    {
      accessor: "LAST_MODIFIED_DATE",
      columnName: "Last Modified date",
      sequence: 10,
      alignment: "center",
      componentType: "default",
      width: 140,
      minWidth: 120,
      maxWidth: 200,
    },
  ],
};
