name: city-admin on krishna window new

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}

# permissions:
#   contents: read

jobs:
  build:
    strategy:
      matrix:
        os-version: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, windows-7]
    runs-on: ${{ matrix.os-version }}


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js and Build
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.os-version }}
      - run: npm install yarn -g
      - run: yarn install

      - run: yarn run build

      - name: Displaying Build is Success
        run: echo "Build is successful!"

