name: city-admin on krishna window new

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}

# permissions:
#   contents: read

jobs:
  build:
    runs-on: admin-panel

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js and Build
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      # - run: npm install yarn -g
      - run: npm ci --legacy-peer-deps
      - run: yarn add @koale/useworker

      - run: npm run build
        env: 
           CI: false

      - name: Displaying Build is Success
        run: echo "Build is successful!"

